/**
 * SpriteDefinitions.js
 * Master Registry of Duke Nukem II Actors.
 * Maps Actor ID -> Name, Type, and the specific Graphic Index (GfxID) to use.
 */

export const SPRITE_MAP = {};

// Helper to register actors
function register(id, name, type, gfxId) {
    SPRITE_MAP[id] = { name, type, gfxId };
}

// --- GENERATION LOGIC ---
// We use the Python Gallery logic to determine GfxID
function getGalleryGfxId(id) {
    if (id < 200) return id - 1; // Standard offset
    if (id === 200) return -1;   // Empty slot
    if (id === 201) return 201;  // EXCEPTION: Red Box Turkey maps 1:1
    if (id >= 202) return id - 1; // Standard offset (Result: 202->201, sharing art)
    return -1;
}

// --- BULK REGISTRATION ---
// Canonical list from your research
const RAW_NAMES = {
    0: "HOVERBOT", 1: "EXPLOSION_FX_1", 2: "EXPLOSION_FX_2", 3: "FLAME_FX",
    4: "GREEN_CREATURE_EYE_FX_L", 5: "DUKE_L", 6: "DUKE_R", 7: "DUKE_ROCKET_UP",
    8: "DUKE_ROCKET_DOWN", 9: "DUKE_ROCKET_LEFT", 10: "DUKE_ROCKET_RIGHT", 11: "SMOKE_PUFF_FX",
    12: "HOVERBOT_DEBRIS_1", 13: "HOVERBOT_DEBRIS_2", 14: "NUCLEAR_WASTE_CAN_EMPTY", 15: "NUCLEAR_WASTE_CAN_DEBRIS_1",
    16: "NUCLEAR_WASTE_CAN_DEBRIS_2", 17: "NUCLEAR_WASTE_CAN_DEBRIS_3", 18: "NUCLEAR_WASTE_CAN_DEBRIS_4", 19: "ROCKET_LAUNCHER",
    20: "FLAME_THROWER", 21: "DUKE_FLAME_SHOT_UP", 22: "NORMAL_WEAPON", 23: "LASER",
    24: "DUKE_LASER_SHOT_HORIZONTAL", 25: "DUKE_LASER_SHOT_VERTICAL", 26: "REGULAR_SHOT_HORIZONTAL", 27: "REGULAR_SHOT_VERTICAL",
    28: "HEALTH_MOLECULE", 29: "MENU_FONT_GRAYSCALE", 31: "BIG_GREEN_CAT_L", 32: "BIG_GREEN_CAT_R",
    33: "MUZZLE_FLASH_UP", 34: "MUZZLE_FLASH_DOWN", 35: "MUZZLE_FLASH_LEFT", 36: "MUZZLE_FLASH_RIGHT",
    37: "CIRCUIT_CARD", 38: "FLAME_THROWER_BOT_R", 39: "FLAME_THROWER_BOT_L", 40: "FLAME_THROWER_FIRE_R",
    41: "FLAME_THROWER_FIRE_L", 42: "RED_BOX_BOMB", 43: "NUCLEAR_EXPLOSION", 44: "BONUS_GLOBE_SHELL",
    45: "BLUE_BONUS_GLOBE_1", 46: "BLUE_BONUS_GLOBE_2", 47: "BLUE_BONUS_GLOBE_3", 48: "BLUE_BONUS_GLOBE_4",
    49: "WATCHBOT", 50: "TELEPORTER_1", 51: "TELEPORTER_2", 52: "RAPID_FIRE_ICON",
    53: "RAPID_FIRE", 54: "ROCKET_LAUNCHER_TURRET", 55: "ENEMY_ROCKET_LEFT", 56: "ENEMY_ROCKET_UP",
    57: "ENEMY_ROCKET_RIGHT", 58: "WATCHBOT_CONTAINER_CARRIER", 59: "WATCHBOT_CONTAINER", 60: "WATCHBOT_CONTAINER_DEBRIS_1",
    61: "WATCHBOT_CONTAINER_DEBRIS_2", 62: "BOMBER_PLANE", 63: "MINI_NUKE", 64: "BOUNCING_SPIKE_BALL",
    65: "FIRE_BOMB_FIRE", 66: "ELECTRIC_REACTOR", 67: "SLIME_BLOB", 68: "SLIME_CONTAINER",
    69: "HOVERBOT_TELEPORT_FX", 70: "SLIME_BLOB_2", 71: "DUKE_DEATH_PARTICLES", 72: "BONUS_GLOBE_DEBRIS_1",
    73: "BONUS_GLOBE_DEBRIS_2", 74: "WHITE_CIRCLE_FLASH_FX", 75: "NUCLEAR_WASTE", 76: "MINI_NUKE_SMALL",
    77: "HUD_FRAME_BACKGROUND", 78: "SNAKE", 79: "CAMERA_ON_CEILING", 80: "CAMERA_ON_FLOOR",
    81: "CEILING_SUCKER", 82: "META_MEDIUMHARD_ONLY", 83: "META_HARD_ONLY", 84: "SMOKE_CLOUD_FX",
    85: "REACTOR_FIRE_L", 86: "REACTOR_FIRE_R", 87: "DUKES_SHIP_R", 88: "DUKES_SHIP_L",
    89: "DUKES_SHIP_AFTER_EXITING_L", 90: "DUKES_SHIP_AFTER_EXITING_R", 91: "DUKES_SHIP_LASER_SHOT", 92: "DUKES_SHIP_EXHAUST_FLAMES",
    93: "SUPER_FORCE_FIELD_L", 94: "BIOLOGICAL_ENEMY_DEBRIS", 95: "MISSILE_BROKEN", 96: "MISSILE_DEBRIS",
    97: "WALL_WALKER", 98: "EYEBALL_THROWER_L", 99: "EYEBALL_THROWER_R", 100: "EYEBALL_PROJECTILE",
    101: "BOSS_EPISODE_2", 102: "DYNAMIC_GEOMETRY_1", 103: "META_DYNGEO_MARKER_1", 104: "META_DYNGEO_MARKER_2",
    106: "DYNAMIC_GEOMETRY_2", 107: "MESSENGER_DRONE_BODY", 108: "MESSENGER_DRONE_ENGINE_R", 109: "MESSENGER_DRONE_ENGINE_L",
    110: "MESSENGER_DRONE_ENGINE_DOWN", 111: "MESSENGER_DRONE_FLAME_DOWN", 112: "MESSENGER_DRONE_FLAME_L", 113: "MESSENGER_DRONE_FLAME_R",
    114: "CLOAKING_DEVICE", 115: "HOVERBOT_GENERATOR", 116: "DYNAMIC_GEOMETRY_3", 117: "SLIME_PIPE",
    118: "SLIME_DROP", 119: "FORCE_FIELD", 120: "CIRCUIT_CARD_KEYHOLE", 121: "BLUE_KEY",
    122: "BLUE_KEY_KEYHOLE", 123: "SCORE_NUMBER_FX_100", 124: "SCORE_NUMBER_FX_500", 125: "SCORE_NUMBER_FX_2000",
    126: "SCORE_NUMBER_FX_5000", 127: "SCORE_NUMBER_FX_10000", 128: "SLIDING_DOOR_VERTICAL", 129: "KEYHOLE_MOUNTING_POLE",
    130: "BLOWING_FAN", 131: "LASER_TURRET", 132: "SLIDING_DOOR_HORIZONTAL", 133: "RESPAWN_CHECKPOINT",
    134: "SKELETON", 135: "ENEMY_LASER_SHOT_R", 136: "ENEMY_LASER_SHOT_L", 137: "DYNAMIC_GEOMETRY_4",
    138: "DYNAMIC_GEOMETRY_5", 139: "EXIT_TRIGGER", 140: "LASER_TURRET_MOUNTING_POST", 141: "DYNAMIC_GEOMETRY_6",
    142: "DYNAMIC_GEOMETRY_7", 143: "DYNAMIC_GEOMETRY_8", 144: "MISSILE_INTACT", 146: "PRESS_ANY_KEY",
    147: "ENEMY_LASER_MUZZLE_FLASH_L", 148: "ENEMY_LASER_MUZZLE_FLASH_R", 149: "MISSILE_EXHAUST_FLAME", 150: "METAL_GRABBER_CLAW",
    151: "HOVERING_LASER_TURRET", 152: "METAL_GRABBER_CLAW_DEBRIS_1", 153: "METAL_GRABBER_CLAW_DEBRIS_2", 154: "SPIDER",
    155: "N", 156: "U", 157: "K", 158: "E", 159: "BLUE_GUARD_R", 160: "GAME_CARTRIDGE",
    161: "WHITE_BOX", 162: "GREEN_BOX", 163: "RED_BOX", 164: "BLUE_BOX", 165: "YELLOW_FIREBALL_FX",
    166: "GREEN_FIREBALL_FX", 167: "BLUE_FIREBALL_FX", 168: "SODA_CAN", 169: "COKE_CAN_DEBRIS_1",
    170: "COKE_CAN_DEBRIS_2", 171: "BLUE_GUARD_L", 172: "SUNGLASSES", 173: "PHONE",
    174: "SODA_6_PACK", 175: "DUKE_3D_TEASER_TEXT", 176: "UGLY_GREEN_BIRD", 181: "BOOM_BOX",
    182: "DISK", 183: "TV", 184: "CAMERA", 185: "PC", 186: "CD", 187: "M", 188: "ROTATING_FLOOR_SPIKES",
    189: "GREEN_CREATURE_L", 190: "GREEN_CREATURE_R", 191: "GREEN_CREATURE_EYE_FX_R", 192: "GREEN_CREATURE_SHELL_1_L",
    193: "GREEN_CREATURE_SHELL_2_L", 194: "GREEN_CREATURE_SHELL_3_L", 195: "GREEN_CREATURE_SHELL_4_L", 196: "GREEN_CREATURE_SHELL_1_R",
    197: "GREEN_CREATURE_SHELL_2_R", 198: "GREEN_CREATURE_SHELL_3_R", 199: "GREEN_CREATURE_SHELL_4_R", 200: "BOSS_EPISODE_1",
    201: "RED_BOX_TURKEY", 202: "TURKEY", 203: "RED_BIRD", 204: "DUKE_FLAME_SHOT_DOWN",
    205: "DUKE_FLAME_SHOT_LEFT", 206: "DUKE_FLAME_SHOT_RIGHT", 208: "FLOATING_EXIT_SIGN_R", 209: "ELEVATOR",
    210: "COMPUTER_TERMINAL", 211: "CLOAKING_DEVICE_ICON", 212: "LAVA_PIT", 213: "MESSENGER_DRONE_1",
    214: "MESSENGER_DRONE_2", 215: "MESSENGER_DRONE_3", 216: "MESSENGER_DRONE_4", 217: "BLUE_GUARD_USING_TERMINAL",
    218: "SUPER_FORCE_FIELD_R", 219: "SMASH_HAMMER", 220: "MESSENGER_DRONE_5", 221: "WATER_BODY",
    222: "LAVA_FALL_1", 223: "LAVA_FALL_2", 224: "WATER_FALL_1", 225: "WATER_FALL_2",
    226: "WATER_DROP", 227: "WATER_DROP_SPAWNER", 228: "WATER_FALL_SPLASH_L", 229: "WATER_FALL_SPLASH_CENTER",
    230: "WATER_FALL_SPLASH_R", 231: "LAVA_FOUNTAIN", 232: "SPIDER_SHAKEN_OFF", 233: "WATER_SURFACE",
    234: "WATER_AREA_4x4", 235: "GREEN_ACID_PIT", 236: "RADAR_DISH", 237: "RADAR_COMPUTER_TERMINAL",
    238: "SPECIAL_HINT_GLOBE_ICON", 239: "SPECIAL_HINT_GLOBE", 240: "SPECIAL_HINT_MACHINE", 241: "WINDBLOWN_SPIDER_GENERATOR",
    242: "SPIDER_DEBRIS_2", 243: "SPIDER_BLOWING_IN_WIND", 244: "UNICYCLE_BOT", 246: "FLAME_JET_1",
    247: "FLAME_JET_2", 248: "FLAME_JET_3", 249: "FLAME_JET_4", 250: "AIRLOCK_DEATH_TRIGGER_L",
    251: "AIRLOCK_DEATH_TRIGGER_R", 252: "FLOATING_EXIT_SIGN_L", 253: "AGGRESSIVE_PRISONER", 254: "EXPLOSION_FX_TRIGGER",
    255: "PRISONER_HAND_DEBRIS", 256: "ENEMY_ROCKET_2_UP", 257: "WATER_ON_FLOOR_1", 258: "WATER_ON_FLOOR_2",
    259: "ENEMY_ROCKET_2_DOWN", 260: "BLOWING_FAN_THREADS_ON_TOP", 261: "PASSIVE_PRISONER", 262: "FIRE_ON_FLOOR_1",
    263: "FIRE_ON_FLOOR_2", 265: "BOSS_EPISODE_3", 271: "SMALL_FLYING_SHIP_1", 272: "SMALL_FLYING_SHIP_2",
    273: "SMALL_FLYING_SHIP_3", 274: "T_SHIRT", 275: "VIDEOCASSETTE", 279: "BOSS_EPISODE_4",
    280: "BOSS_EPISODE_4_SHOT", 290: "LETTER_INDICATOR_N", 291: "LETTER_INDICATOR_U", 292: "LETTER_INDICATOR_K",
    293: "LETTER_INDICATOR_E", 294: "LETTER_INDICATOR_M", 296: "FLOATING_ARROW", 297: "NEWS_REPORTER_BABBLE",
    299: "RIGELATIN_SOLDIER", 300: "RIGELATIN_SOLDIER_SHOT"
};

// Process the raw list into the final map
for (const [idStr, name] of Object.entries(RAW_NAMES)) {
    const id = parseInt(idStr, 10);
    
    // Auto-detect type based on name
    let type = "decorative";
    const n = name.toUpperCase();
    
    if (n.includes("DUKE")) type = "player";
    else if (n.includes("BOSS") || n.includes("ENEMY") || n.includes("GUARD") || n.includes("BOT") || n.includes("SKELETON") || n.includes("SPIDER")) type = "enemy";
    else if (n.includes("BOX") || n.includes("BONUS") || n.includes("KEY") || n.includes("COLA") || n.includes("HEALTH") || n.includes("WEAPON") || n.includes("LASER")) type = "bonus";
    else if (n.includes("HAZARD") || n.includes("SPIKE") || n.includes("FIRE") || n.includes("LAVA")) type = "hazard";
    else if (n.includes("FX") || n.includes("FLASH") || n.includes("SMOKE")) type = "fx";
    else if (n.includes("TRIGGER") || n.includes("META")) type = "meta";
    
    register(id, name, type, getGalleryGfxId(id));
}

export function getActorInfo(id) {
    return SPRITE_MAP[id] || { name: `UNKNOWN (${id})`, type: "unknown", gfxId: -1 };
}